#### Multi-Collinearity

In [6]:
import numpy as np

arr = np.array([
    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    [1.2, 2.1, 3.1, 4.1, 5.0, 6.0, 7.0, 8.0, 9.1, 10.2]
]).T

print(arr)
print(arr.shape)

[[ 1.   1.   1.2]
 [ 1.   2.   2.1]
 [ 1.   3.   3.1]
 [ 1.   4.   4.1]
 [ 1.   5.   5. ]
 [ 1.   6.   6. ]
 [ 1.   7.   7. ]
 [ 1.   8.   8. ]
 [ 1.   9.   9.1]
 [ 1.  10.  10.2]]
(10, 3)


In [7]:
np.linalg.inv(np.dot(arr.T, arr))

array([[  0.67713004,   1.89686099,  -1.97309417],
       [  1.89686099,  18.3309417 , -18.40807175],
       [ -1.97309417, -18.40807175,  18.49775785]])

In [8]:
arr = np.array([
    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    [2.4,8.7,4.3,3.2,5.1,9.0,7.9,1.0,9.1,1.2]
]).T

print(arr)
print(arr.shape)

[[ 1.   1.   2.4]
 [ 1.   2.   8.7]
 [ 1.   3.   4.3]
 [ 1.   4.   3.2]
 [ 1.   5.   5.1]
 [ 1.   6.   9. ]
 [ 1.   7.   7.9]
 [ 1.   8.   1. ]
 [ 1.   9.   9.1]
 [ 1.  10.   1.2]]
(10, 3)


In [9]:
np.linalg.inv(np.dot(arr.T, arr))

array([[ 7.73207640e-01, -6.89001790e-02, -5.66968508e-02],
       [-6.89001790e-02,  1.21374859e-02,  4.13103385e-04],
       [-5.66968508e-02,  4.13103385e-04,  1.04864705e-02]])

In [10]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
import pandas as pd

X = df[['X1', 'X2', 'X3']]

vif = pd.DataFrame()
vif["Feature"] = X.columns
vif["VIF"] = [
    variance_inflation_factor(X.values, i)
    for i in range(X.shape[1])
]

print(vif)

ModuleNotFoundError: No module named 'statsmodels'